package oreilly;

import javax.swing.JOptionPane;

public class ConfigUI extends javax.swing.JFrame
{

    Graph m;

    public ConfigUI(Graph m)
    {
        initComponents();
        this.m = m;
        txfBaseURL.setText(m.getBaseUrl());
        txfScenarios.setText(m.getNumScenariosToGenerate() + "");
        fillInPhaseBox();
    }

    private void fillInPhaseBox()
    {
        int s = m.getNumPhases();
        cbxDeletePhase.removeAllItems();
        for (int i = 0; i < s; i++)
        {
            cbxDeletePhase.addItem((Integer) i);
        }
        try
        {
            cbxDeletePhase.setSelectedIndex(0);
        } catch (IllegalArgumentException e)
        {

        }
        txaPhases.setText(m.getPhases());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfBaseURL = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfArrival = new javax.swing.JTextField();
        txfDuration = new javax.swing.JTextField();
        btnAddPhase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPhases = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txfScenarios = new javax.swing.JTextField();
        btnScenarios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDeletePhase = new javax.swing.JButton();
        cbxDeletePhase = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIG");

        jLabel2.setText("Base URL");

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel3.setText("Phases");

        jLabel4.setText("Duration");

        jLabel5.setText("Arrival Rate (/s)");

        btnAddPhase.setText("Add Phase");
        btnAddPhase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddPhaseActionPerformed(evt);
            }
        });

        txaPhases.setColumns(20);
        txaPhases.setRows(5);
        jScrollPane1.setViewportView(txaPhases);

        jLabel6.setText("Number of  Scenarios to Generate");

        btnScenarios.setText("Change");
        btnScenarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnScenariosActionPerformed(evt);
            }
        });

        jLabel7.setText("Delete Phase");

        btnDeletePhase.setText("Delete Phase");
        btnDeletePhase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeletePhaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfScenarios))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfBaseURL, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnScenarios, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfArrival))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbxDeletePhase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(txfDuration)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddPhase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePhase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfBaseURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfScenarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScenarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPhase, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfArrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbxDeletePhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeletePhase)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangeActionPerformed
    {//GEN-HEADEREND:event_btnChangeActionPerformed
        String t = txfBaseURL.getText().trim();
        if (!t.equals(""))
        {
            m.setBaseUrl(txfBaseURL.getText());
        } else
        {
            JOptionPane.showMessageDialog(null, "URL required!");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnAddPhaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPhaseActionPerformed
    {//GEN-HEADEREND:event_btnAddPhaseActionPerformed
        String d = txfDuration.getText().trim();
        String a = txfArrival.getText().trim();
        if (!d.equals("") && !a.equals(""))
        {
            m.addPhase(Integer.parseInt(d), Integer.parseInt(a));
            txaPhases.setText(m.getPhases());
            fillInPhaseBox();
        } else
        {
            JOptionPane.showMessageDialog(null, "Duration or arrival rate missing!");
        }
    }//GEN-LAST:event_btnAddPhaseActionPerformed

    private void btnScenariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnScenariosActionPerformed
    {//GEN-HEADEREND:event_btnScenariosActionPerformed
        String s = txfScenarios.getText().trim();
        if (!s.equals(""))
        {
            m.setNumScenariosToGenerate(Integer.parseInt(s));
        } else
        {
            JOptionPane.showMessageDialog(null, "Number of scenarios missing!");
        }
    }//GEN-LAST:event_btnScenariosActionPerformed

    private void btnDeletePhaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeletePhaseActionPerformed
    {//GEN-HEADEREND:event_btnDeletePhaseActionPerformed
        if (cbxDeletePhase.getSelectedItem() != null)
        {
            int id = (Integer) cbxDeletePhase.getSelectedItem();
            m.deletePhase(id);
            fillInPhaseBox();
        } else
        {
            JOptionPane.showMessageDialog(null, "No phase selected!");
        }
    }//GEN-LAST:event_btnDeletePhaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPhase;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDeletePhase;
    private javax.swing.JButton btnScenarios;
    private javax.swing.JComboBox<Integer> cbxDeletePhase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaPhases;
    private javax.swing.JTextField txfArrival;
    private javax.swing.JTextField txfBaseURL;
    private javax.swing.JTextField txfDuration;
    private javax.swing.JTextField txfScenarios;
    // End of variables declaration//GEN-END:variables
}
