package oreilly;

import javax.swing.JOptionPane;

public class ConfigUI extends javax.swing.JFrame
{

    Graph graph;

    public ConfigUI(Graph m)
    {
        initComponents();
        this.graph = m;
        txfBaseURL.setText(m.getBaseUrl());
        txfScenarios.setText(m.getNumScenariosToGenerate() + "");
        fillInPhaseBoxMain();
        fillInPhaseBoxSingle();
    }

    private void fillInPhaseBoxMain()
    {
        int numPhases = graph.getNumPhasesMain();
        cbxDeletePhase.removeAllItems();
        for (int i = 0; i < numPhases; i++)
        {
            cbxDeletePhase.addItem((Integer) i);
        }
        try
        {
            cbxDeletePhase.setSelectedIndex(0);
        } catch (IllegalArgumentException e)
        {

        }
        txaPhases.setText(graph.getPhasesMain());
    }
    
    private void fillInPhaseBoxSingle()
    {
        int numPhases = graph.getNumPhasesSingle();
        cbxDeletePhase1.removeAllItems();
        for (int i = 0; i < numPhases; i++)
        {
            cbxDeletePhase1.addItem((Integer) i);
        }
        try
        {
            cbxDeletePhase1.setSelectedIndex(0);
        } catch (IllegalArgumentException e)
        {

        }
        txaPhases1.setText(graph.getPhasesSingle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfBaseURL = new javax.swing.JTextField();
        btnChange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfArrival = new javax.swing.JTextField();
        txfDuration = new javax.swing.JTextField();
        btnAddPhase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPhases = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txfScenarios = new javax.swing.JTextField();
        btnScenarios = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnDeletePhase = new javax.swing.JButton();
        cbxDeletePhase = new javax.swing.JComboBox<>();
        btnAddPhase1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaPhases1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnDeletePhase1 = new javax.swing.JButton();
        cbxDeletePhase1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txfArrival1 = new javax.swing.JTextField();
        txfDuration1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONFIG");

        jLabel2.setText("Base URL");

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChangeActionPerformed(evt);
            }
        });

        jLabel3.setText("Main Phases");

        jLabel4.setText("Duration");

        jLabel5.setText("Arrival Rate (/s)");

        btnAddPhase.setText("Add Phase");
        btnAddPhase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddPhaseActionPerformed(evt);
            }
        });

        txaPhases.setColumns(20);
        txaPhases.setRows(5);
        jScrollPane1.setViewportView(txaPhases);

        jLabel6.setText("Number of  Scenarios to Generate");

        btnScenarios.setText("Change");
        btnScenarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnScenariosActionPerformed(evt);
            }
        });

        jLabel7.setText("Delete Phase");

        btnDeletePhase.setText("Delete Phase");
        btnDeletePhase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeletePhaseActionPerformed(evt);
            }
        });

        btnAddPhase1.setText("Add Phase");
        btnAddPhase1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddPhase1ActionPerformed(evt);
            }
        });

        txaPhases1.setColumns(20);
        txaPhases1.setRows(5);
        jScrollPane2.setViewportView(txaPhases1);

        jLabel8.setText("Delete Phase");

        btnDeletePhase1.setText("Delete Phase");
        btnDeletePhase1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeletePhase1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Singular Scenario Test Phases");

        jLabel10.setText("Duration");

        jLabel11.setText("Arrival Rate (/s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfScenarios))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfBaseURL, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnScenarios, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfArrival1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cbxDeletePhase1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(40, 40, 40)
                                .addComponent(txfDuration1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddPhase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePhase1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfArrival))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbxDeletePhase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(txfDuration)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddPhase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletePhase))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfBaseURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfScenarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScenarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPhase, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfArrival, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbxDeletePhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeletePhase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPhase1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfDuration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfArrival1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeletePhase1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbxDeletePhase1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangeActionPerformed
    {//GEN-HEADEREND:event_btnChangeActionPerformed
        String baseURL = txfBaseURL.getText().trim();
        if (!baseURL.equals(""))
        {
            graph.setBaseUrl(txfBaseURL.getText());
        } else
        {
            JOptionPane.showMessageDialog(null, "URL required!");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnAddPhaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPhaseActionPerformed
    {//GEN-HEADEREND:event_btnAddPhaseActionPerformed
        String duration = txfDuration.getText().trim();
        String arrivalRate = txfArrival.getText().trim();
        if (!duration.equals("") && !arrivalRate.equals(""))
        {
            graph.addPhaseMain(Integer.parseInt(duration), Integer.parseInt(arrivalRate));
            txaPhases.setText(graph.getPhasesMain());
            fillInPhaseBoxMain();
        } else
        {
            JOptionPane.showMessageDialog(null, "Duration or arrival rate missing!");
        }
    }//GEN-LAST:event_btnAddPhaseActionPerformed

    private void btnScenariosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnScenariosActionPerformed
    {//GEN-HEADEREND:event_btnScenariosActionPerformed
        String numScenariosToGenerate = txfScenarios.getText().trim();
        if (!numScenariosToGenerate.equals(""))
        {
            graph.setNumScenariosToGenerate(Integer.parseInt(numScenariosToGenerate));
        } else
        {
            JOptionPane.showMessageDialog(null, "Number of scenarios missing!");
        }
    }//GEN-LAST:event_btnScenariosActionPerformed

    private void btnDeletePhaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeletePhaseActionPerformed
    {//GEN-HEADEREND:event_btnDeletePhaseActionPerformed
        if (cbxDeletePhase.getSelectedItem() != null)
        {
            int phaseID = (Integer) cbxDeletePhase.getSelectedItem();
            graph.deletePhaseMain(phaseID);
            fillInPhaseBoxMain();
        } else
        {
            JOptionPane.showMessageDialog(null, "No phase selected!");
        }
    }//GEN-LAST:event_btnDeletePhaseActionPerformed

    private void btnAddPhase1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddPhase1ActionPerformed
    {//GEN-HEADEREND:event_btnAddPhase1ActionPerformed
        String duration = txfDuration1.getText().trim();
        String arrivalRate = txfArrival1.getText().trim();
        if (!duration.equals("") && !arrivalRate.equals(""))
        {
            graph.addPhaseSingle(Integer.parseInt(duration), Integer.parseInt(arrivalRate));
            txaPhases1.setText(graph.getPhasesSingle());
            fillInPhaseBoxSingle();
        } else
        {
            JOptionPane.showMessageDialog(null, "Duration or arrival rate missing!");
        }
    }//GEN-LAST:event_btnAddPhase1ActionPerformed

    private void btnDeletePhase1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeletePhase1ActionPerformed
    {//GEN-HEADEREND:event_btnDeletePhase1ActionPerformed
        if (cbxDeletePhase1.getSelectedItem() != null)
        {
            int phaseID = (Integer) cbxDeletePhase1.getSelectedItem();
            graph.deletePhaseSingle(phaseID);
            fillInPhaseBoxSingle();
        } else
        {
            JOptionPane.showMessageDialog(null, "No phase selected!");
        }
    }//GEN-LAST:event_btnDeletePhase1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPhase;
    private javax.swing.JButton btnAddPhase1;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDeletePhase;
    private javax.swing.JButton btnDeletePhase1;
    private javax.swing.JButton btnScenarios;
    private javax.swing.JComboBox<Integer> cbxDeletePhase;
    private javax.swing.JComboBox<Integer> cbxDeletePhase1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txaPhases;
    private javax.swing.JTextArea txaPhases1;
    private javax.swing.JTextField txfArrival;
    private javax.swing.JTextField txfArrival1;
    private javax.swing.JTextField txfBaseURL;
    private javax.swing.JTextField txfDuration;
    private javax.swing.JTextField txfDuration1;
    private javax.swing.JTextField txfScenarios;
    // End of variables declaration//GEN-END:variables
}
